# Generated by Django 4.2.27 on 2025-12-10 12:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Patient's full name", max_length=100)),
                ('age', models.PositiveIntegerField(help_text='Age in years', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)])),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in kg', max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, help_text='Height in cm', max_digits=5)),
                ('bmi', models.DecimalField(blank=True, decimal_places=2, help_text='Body Mass Index (calculated automatically)', max_digits=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HealthData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateField(default=django.utils.timezone.now)),
                ('cholesterol_total', models.PositiveIntegerField(blank=True, help_text='Total cholesterol (mg/dL)', null=True)),
                ('cholesterol_ldl', models.PositiveIntegerField(blank=True, help_text='LDL (bad) cholesterol (mg/dL)', null=True)),
                ('cholesterol_hdl', models.PositiveIntegerField(blank=True, help_text='HDL (good) cholesterol (mg/dL)', null=True)),
                ('tsh_level', models.DecimalField(blank=True, decimal_places=2, help_text='TSH level (mIU/L)', max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_data', to='app.patient')),
            ],
            options={
                'ordering': ['-test_date'],
            },
        ),
        migrations.CreateModel(
            name='SugarReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_date', models.DateField(default=django.utils.timezone.now)),
                ('sugar_before_breakfast', models.PositiveIntegerField(help_text='Fasting sugar level (mg/dL)')),
                ('sugar_after_breakfast', models.PositiveIntegerField(help_text='Post-meal sugar level (mg/dL)')),
                ('notes', models.TextField(blank=True, help_text='Any additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sugar_readings', to='app.patient')),
            ],
            options={
                'ordering': ['-reading_date'],
                'unique_together': {('patient', 'reading_date')},
            },
        ),
    ]
